Tracking file by folder pattern:  migrations
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pycharm\django_manage.py", line 52, in <module>
    run_command()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.3\helpers\pycharm\django_manage.py", line 46, in run_command
    run_module(manage_file, None, '__main__', True)
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:/xadmin_django\manage.py", line 4, in <module>
    from message import views
  File "D:\xadmin_django\apps\message\views.py", line 4, in <module>
    from .models import UserMessage
  File "D:\xadmin_django\apps\message\models.py", line 6, in <module>
    class UserMessage(models.Model):
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\Administrator\Anaconda3\envs\online_education-py36-Django19\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

把manage.py的from message import views注释掉
# from message import views